version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    ports:
        - '8000:80'
    links: 
        - "db:database"
  db:
    image: postgres